language: node_js
sudo: false
node_js:
  - '10'

cache:
  directories:
    - '.eslintcache'
    - 'node_modules'

git:
  depth: 10
branches:
  only:
    - master

install:
  - npm install -g jest
  - npm install -g codacy-coverage
  - npm ci

script:
  # Tests with covarage
  - npm run test-ci
  # Report coverage on codacy
  - cat ./coverage/lcov.info | codacy-coverage --projectName checkif --token 1f405c7cc58b480d8e1f96a05a77777a --verbose
